### ISSUE TITLE
Compatibility issue with Django 1.11

### ISSUE THREAD

**Issue by hodossy** [callowayproject/django-categories#134]
Django 1.11 no longer accepts RequestContext or Context object:

https://docs.djangoproject.com/en/1.11/releases/1.11/#django-template-backends-django-template-render-prohibits-non-dict-context

This results in a TypeError when responses are rendered for e.g. the admin page.

    TypeError: context must be a dict rather than RequestContext.

**Comment by epicserve** [comment]
@hodossy, feel free to submit a PR.

**Comment by qari** [comment]
I have same problem in admin

`

Request Method: | GET
-- | --
http://0.0.0.0:8000/admin/categories/category/
1.11.5
TypeError
context must be a dict rather than RequestContext.
/usr/local/lib/python3.5/site-packages/django/template/context.py in make_context, line 287
/usr/local/bin/python
3.5.3
['/usr/src/app',  '/usr/local/lib/python35.zip',  '/usr/local/lib/python3.5',  '/usr/local/lib/python3.5/plat-linux',  '/usr/local/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/site-packages',  '/usr/src/app',  '/usr/local/lib/python3.5/site-packages/odf',  '/usr/local/lib/python3.5/site-packages/odf',  '/usr/local/lib/python3.5/site-packages/odf',  '/usr/local/lib/python3.5/site-packages/odf',  '/usr/local/lib/python3.5/site-packages/odf',  '/usr/local/lib/python3.5/site-packages/odf',  '/usr/local/lib/python3.5/site-packages/odf']
Вт, 19 Сен 2017 07:13:45 +0000


`

**Comment by Nomados** [comment]
I have the same issue

**Comment by Nomados** [comment]
The problems in 'admin' remains. The tree_editor.py cannot be rendered

**Comment by qari** [comment]
Categories | 1.5.3
-- | --
The problems in 'admin' remain.

**Comment by qari** [comment]
How long wait https://github.com/callowayproject/django-categories/pull/135 ?

**Comment by lggwettmann** [comment]
This was merged in February, right?

**Comment by epicserve** [comment]
@lggwettmann, it should be compatible with Django 2.0 and Django 1.11.
